### ISSUE TITLE
Show non-variable comparison side by side

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-type-tools#15]
Would be nice to duplicate the `<article>` but not apply any `variation-settings` to it, so that you can see what VF is bringing :) 

<img width="1920" alt="screen shot 2017-10-27 at 09 47 20" src="https://user-images.githubusercontent.com/261579/32107180-d8513ec0-bafb-11e7-95d0-dc2d0983efaf.png">

**Comment by davelab6** [comment]
Discussed this with @dberlow today, and he recommended NOT implementing this, but documenting that to meet that user need, using 2 windows :)

<img width="1899" alt="screen shot 2019-02-22 at 5 52 48 pm" src="https://user-images.githubusercontent.com/261579/53275867-bf29eb80-36ca-11e9-9e6b-4d584d94779b.png">

So to close this, I will make a PR update. 

However, @irink suggest that a toggle mode for doing comparisons of before/after would be more useful.

**Comment by dberlow** [comment]
What Dave means by comparisons in this case is that the ramp, Or any other view,
 could be saved with the particular set of styles used,
 Put in menu, or a list of saved such pages
 And then the user could switch back-and-forth quickly to see the difference between to settings of the whole page.

**Comment by davelab6** [comment]
I went back to the original discussion and it seems this request was much more simple, in that it is a request for being the non variable family compared to the variable one, so that the (dramatic) difference that optical size makes can be clearly demonstrated. But still the result in the same; use 2 windows :)

**Comment by dberlow** [comment]
I have confirmed non-var installation and function as required for s-b-s browser window compare,

**Comment by chrissam42** [comment]
Coincidentally, @cjdunn has been asking me about creating an overlay proof to compare variable to non-var versions of the same font. I was debating whether it makes sense to create a whole separate tool for that, or to lay that onto typetools somehow.

**Comment by dberlow** [comment]
I understand the need for overlay in proofing and plan to get there soon. 
I assume that
  a second layer of the type on our pages can be defined with a transparent background 
  and a default fill color for the 2nd  layer defined 
  And a stroke option with a default stroke and color,
  And switching the two layers.
And a logic for which layouts get this option and which don’t.

In the mean time, i’m Just looking to do this via the software we have and side-by-side browser compares.

Let me know your thoughts I hope to get to this in the next couple weeks
