### ISSUE TITLE
Stacked Maker

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/variable-type-tools#31]
#30 Default
![screen shot 2018-03-21 at 12 21 24 pm](https://user-images.githubusercontent.com/7713203/37723700-60cce986-2d05-11e8-82e4-cd0fc8b3c859.png)

five lines
Default Column width 50
equal line space between each line

Line 1 wght (max) -  wdth (max) - size to fit
Line 2 wght (min) - wdth (max) - size to fit
Line 3 wdth (mid) -  wdth (mid) - size to fit
Line 4 wght (min)  - wdth (min) - size to fit
Line 5 wdth (max) -  wdth (max) - size to fit

New line or new text 
curser center type fills space from middle out
wght (max)  wdth (max) size to fit
set max size for first letter 400, fit at 3rd letter
Slide wght - Size to fit
Slide wdth - Size to fit

Slide 1
![screen shot 2018-03-21 at 12 08 51 pm](https://user-images.githubusercontent.com/7713203/37723834-b7af1dd2-2d05-11e8-972d-74811ceee2ab.png)

Slide 2
![screen shot 2018-03-21 at 12 09 21 pm](https://user-images.githubusercontent.com/7713203/37723835-b7dedec8-2d05-11e8-9e00-18779086371a.png)

Slide 3
![screen shot 2018-03-21 at 12 09 49 pm](https://user-images.githubusercontent.com/7713203/37723836-b8481f82-2d05-11e8-99c8-9557a4db665f.png)

Slide 4
![screen shot 2018-03-21 at 12 10 57 pm](https://user-images.githubusercontent.com/7713203/37723865-d2f6fa4c-2d05-11e8-810c-ff816f52c880.png)

Line space equals word space

Order of Change
- user changes wght - adjust wdth before size
- user changes wdth - adjust wght before size
- User changes size - adjust wdth before wght
- Once wght or wdth are max or min - adjust size to fit

as user types

![screen shot 2018-03-21 at 12 58 21 pm](https://user-images.githubusercontent.com/7713203/37724657-a754dde4-2d07-11e8-99c5-545e9cf3a3c4.png)

wght (max) wdth (max) size (max)

![screen shot 2018-03-21 at 12 58 42 pm](https://user-images.githubusercontent.com/7713203/37724667-ae3ccd10-2d07-11e8-90c2-3abfb30b13fa.png)
 
wght (mid) wdth (mid) adjust size (max)

![screen shot 2018-03-21 at 1 06 15 pm](https://user-images.githubusercontent.com/7713203/37725165-b71358ae-2d08-11e8-8d98-f8af7e597984.png)

**Comment by dberlow** [comment]
This is closed and moved into videoproof issue #3
