### ISSUE TITLE
"Verbose" changes Logo pogo view

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/variable-type-tools#40]
In some fonts such as Dunbar and Escrowvar, the "verbose font variation settings" changes the view for me in Safari (which I don’t think it should at this point, right?). Also it does not seem to affect the CSS if that is also shown.

![screen shot 2018-04-16 at 5 08 13 pm](https://user-images.githubusercontent.com/6578861/38835195-d127f5c0-4198-11e8-8479-d13e5b173987.png)
![screen shot 2018-04-16 at 5 08 10 pm](https://user-images.githubusercontent.com/6578861/38835196-d1382972-4198-11e8-9bce-d8a0c78e44b8.png)

**Comment by dberlow** [comment]
Closing if resolved?
