### ISSUE TITLE
Option to view default and extreme values

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/variable-type-tools#41]
This might be just too much, but I would find value in being able to quickly see the default values and extreme values for all axes all at once (labeled on the sliders?), to quickly get a sense of the designspace and its extent.

**Comment by dberlow** [comment]
This has been resolved at videotools.typenetwork.com. 
1. Load font
2. Play video of default tour, 
3. or step through keyframes of default tour.
Safer driving while looking at vfonts.

For more issues: https://github.com/TypeNetwork/videoproof/issues
