### ISSUE TITLE
Logo Pogo as Meta link/button?

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-type-tools#55]
The "logo pogo" layout is currently access from the top-most left-sidebar dropdown, and then opens a layout that allows you to type set a small amount of text and download it as an SVG. 

The [`/logopogo/logopogo.php`](https://github.com/TypeNetwork/variable-type-tools/blob/8dc0c6926462f6879d1435ce0ca7d1283b7ed86a/logopogo/logopogo.php) file doesn't actually have any logic, all the logic is in [`/logopogo/logopogo.js`](https://github.com/TypeNetwork/variable-type-tools/blob/8dc0c6926462f6879d1435ce0ca7d1283b7ed86a/logopogo/logopogo.js)

So, I wonder that this could, in addition to being its own "logo maker" layout, become one of the "meta" options at the end of the left-sidebar (alongside "Reset to font defaults" and "Grab latest font files") so that a user can get an SVG out of any page.

**Comment by dberlow** [comment]
So, I think this is closed.
