### ISSUE TITLE
Controls for letter-spacing and word-spacing

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-type-tools#58]
When reviewing Roboto variable fonts today with @dberlow I wanted to adjust letter-spacing to replicate the Material Design typography guidelines :)

DB also suggested a word space control.

But these should not be shown immediately to users, but 'hidden' behind some expander widget, because we want to turn over tracking and word spacing to a justification algorithm.

**Comment by dberlow** [comment]
I am taking the liberty of moving all such issues as this to:

https://github.com/TypeNetwork/videoproof/issues/3
