### ISSUE TITLE
Inputs in pits

### ISSUE THREAD

**Issue by chrissam42** [TypeNetwork/variable-type-tools#60]
Reported by @dberlow:

;)
I’m having a lot of issues trying to compose templates for specimens in typetools. I need to be able to set up the size of the line spacing of repeating samples and just change one thing about the type like wght or wdth, or,set a series of paragraphs at different opsz with specific linespacing.

Inputs to size and linespacing are not being retained when reselecting an already manually specified text block.

Manual Linespacing input is being accepted, but Automation of linespacing is reactivated on Re selection of a paragraph. Turning off automatic linespacing should be enabled.

Input of size is being mashed from, e.g 10, to 9.7665i. While it may be true that after a 10 is input, it gets translated into a number of pixels and the actual size is less or more than 10, I don’t care about the unrounded size. I care that when I input 10 whatever happens is going to happen the same every time I input 10 and it’s going to stay 10 on reselection.

Let me know the possible timing of this, thanks.

**Comment by chrissam42** [comment]
The cumulative weight of typetools bugs is finally heavy enough to overcome my inertia of ignoring them. Between this, #59, and the Safari default-opsz bug, typetools is starting to feel unusable. Will investigate this week.

**Comment by dberlow** [comment]
Thanks! It’s at least more stable than illustrator.;) I look forward to your decisions.

On May 25, 2019, at 4:06 PM, Chris Lewis <notifications@github.com> wrote:

The cumulative weight of typetools bugs is finally heavy enough to overcome my inertia of ignoring them. Between this, #59, and the Safari default-opsz bug, typetools is starting to feel unusable. Will investigate this week.

**Comment by chrissam42** [comment]
I've added a workaround for the Safari default-opsz bug (where Safari ignores the font-variation-settings opsz value if it is the default, and instead sets `opsz` to match the font size). Now if you set the slider to the default (e.g. 14 in Amstelvar) it will add 0.01 during the conversion from sliders to CSS.

**Comment by chrissam42** [comment]
Okay, I believe most of the issues surrounding this have been improved. Most of these were side-effects of switching from `px` to `pt` as the fundamental typographic unit.

Rounding issues in general could still be improved... Javascript is particularly bad about almost-integers like 13.9999 cropping up after doing math. I'll try to do some smart rounding to avoid these ugly decimals in the input boxes.

**Comment by dberlow** [comment]
Thanks, it's much better in linespacing and all but T2... in safari?

Latest amstelvar in safari...
I input "14" for T2, select something else and "13.999999523162842" replaces my input. Can't stop it.

But not Chrome. I input 14 for  T2 and itremains 14...

It seems to switcheroo in H!, where Chrome ends up unrounded and Safiar is rounded. 

Do you want to switch to ems? Rems or something else for size and linespace?
<img width="1630" alt="Chrome:Safari T2" src="https://user-images.githubusercontent.com/1956494/58760239-2eea1680-8503-11e9-9857-d22fdacda114.png">
<img width="973" alt="Chrome:Safari H2" src="https://user-images.githubusercontent.com/1956494/58760240-2eea1680-8503-11e9-8b6d-b8f43e53106c.png">

**Comment by chrissam42** [comment]
I've added rounding for the size/leading inputs.
