### ISSUE TITLE
Black menu bar

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/variable-type-tools#62]
The typetools and video tools apps both show a full menu of TN options.

I think it’s best right away to limit those options to the “type Network” at the far left, which provides access to the Tn home page.

Can this be done easily and quickly?

**Comment by chrissam42** [comment]
I've removed them from both. Our host Webfaction seems to have changed something about their DNS setup, so I am seeing a lot of security warnings and other errors. Will clear that up today.

**Comment by dberlow** [comment]
Thank you.

On Jul 8, 2019, at 1:07 PM, Chris Lewis <notifications@github.com> wrote:

I've removed them from both. Our host Webfaction seems to have changed something about their DNS setup, so I am seeing a lot of security warnings and other errors. Will clear that up today.
