### ISSUE TITLE
Show Github Link at bottom of left sidebar

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-type-tools#66]
As a user, when I visit https://typetools.typenetwork.com, I expect to fine a link to the project's source Github Repo (https://github.com/TypeNetwork/variable-type-tools) and a link to the issue tracker (https://github.com/TypeNetwork/variable-type-tools/issues/) with a solicitation to file issue with bugs or feature ideas. 

This should be done in a similar way to https://github.com/TypeNetwork/videoproof/issues/2 and https://github.com/TypeNetwork/variable-fonts-info-site/issues/106

**Comment by dberlow** [comment]
I’d like to propose the same solutions that proposed at,
https://github.com/TypeNetwork/videoproof/issues/2
linking in the bottom bar to this repo, and it’s issues section for bugs and feature reqs.

**Comment by chrissam42** [comment]
Duplicate of #65.
