### ISSUE TITLE
Add button to Swap Colors

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-type-tools#72]
Almost every time I use TypeTool, I want to swap the fg/bg colors:

<img width="202" alt="Screen Shot 2019-10-18 at 5 03 21 PM" src="https://user-images.githubusercontent.com/261579/67128282-36b40a00-f1c9-11e9-9622-f9128c42bdb3.png">

I suggest using an icon like this, inbetween the 2 colored square icons.

https://material.io/resources/icons/?search=swap&icon=swap_horizontal_circle&style=baseline

**Comment by chrissam42** [comment]
Ha, I had that same reaction and so I added a swap button to videoproof long ago. Will do.

**Comment by dberlow** [comment]
Thanks for the reminder!

On Oct 18, 2019, at 5:06 PM, Chris Lewis <notifications@github.com> wrote:

Ha, I had that same reaction and so I added a swap button to videoproof long ago. Will do.
