### ISSUE TITLE
Issue with inverse colors

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/variable-type-tools#74]
Only problem is in Composition model where selection of the desired paragraph disables reversing of color
![BF8344CE-541E-4F54-A780-CA16756B2353](https://user-images.githubusercontent.com/1956494/74459600-952c8480-4e59-11ea-945a-8eeeb70fe842.png)

**Comment by chrissam42** [comment]
I've changed this to an outline and matched the blue of the size text.

**Comment by dberlow** [comment]
Can we chat about the “large” composition making its own rap?
