### ISSUE TITLE
Default rendering color

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/variable-type-tools#75]
The default rendering color for black is showing up differently for Classic vs. Extremo.
![Roboto color change 001](https://user-images.githubusercontent.com/1956494/75156419-18fb3200-56e0-11ea-97b2-79dce7a02816.jpeg)

it shouldn't.

thanks.

**Comment by chrissam42** [comment]
Pulled my hair out for a while, and it turns out that custom added fonts were inheriting the TN body color, which is #333. I don't know why it happened only for them and not the "built-in" fonts. Anyway I've overridden the TN body text color for typetools.
