### ISSUE TITLE
Col control stopped working?

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-type-tools#90]
On https://variable-type-tools.appspot.com currently the col width control isn't working; it adjusts line-height but doesn't wrap.

**Comment by graphicore** [comment]
I can't reproduce this, for me (Chrome, Firefox) line-length changes and lines wrap accordingly. Is there anything more specific I need to do?

**Comment by davelab6** [comment]
Works for me now. Weird. Maybe it was caused by copy & paste?

**Comment by graphicore** [comment]
> Maybe it was caused by copy & paste?

I have no idea, but when I'll come around at this part of the code, I may find out what can cause this.
